name: Keep Hugging Face Space Alive

on:
  schedule:
    # רץ כל 24 שעות ב-00:00 בלילה
    - cron: '0 0 * * *'
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Space
        run: |
          curl -I https://rivka-karp-naturalcli.hf.space
